# Generated by Django 3.0.5 on 2020-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='a', verbose_name='Адрес или район'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_data',
            field=models.TextField(default='a', verbose_name='Контактные данные (телефон, телеграм)'),
            preserve_default=False,
        ),
    ]
