# Generated by Django 3.0.5 on 2020-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200408_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.TextField(default='a', verbose_name='Организация, которую Вы представляете (обязательно для врачей).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(choices=[('moscow', 'Москва'), ('spb', 'Санкт Петербург')], default='moscow', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
    ]
