# Generated by Django 3.0.5 on 2020-04-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='city',
            new_name='city_cached',
        ),
    ]
